### ISSUE TITLE
Update Document: "Brief Wiring Desc.txt"

### ISSUE THREAD

**Issue by Numeri** [Techbrick/Reference#3]
It would be useful to update this document for the RoboRIO.  This way, future programmers and electricians will have a quick guide/reference.

**Comment by MichelfrancisBustillos** [comment]
These types of docs will be stored in the Google Drive and WindChill for now, until we get a better solution

**Comment by Numeri** [comment]
OK. I feel like for electrical/programming, basic info, tutorials, etc. should be kept here, being that "better" solution, but I'm fine if we don't do that too.

**Comment by MichelfrancisBustillos** [comment]
I agree with you, it'd be a better solution at least for the time being (I feel like having our own wiki might be better if this one doesn't offer enough customization options). Go ahead and create a home page for the wiki and we'll start from there
